before_install:
 - chmod +x gradlew
 
script: ./gradlew build
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12

jobs:
  include:
    - stage: deploy
      if: env(SONATYPE_USERNAME) IS present AND type IN (push, api) AND branch IN (master) AND tag IS blank
      jdk: openjdk8
      script: ./gradlew publishToSonatype -PsonatypeUser=$SONATYPE_USER -PsonatypePassword=$SONATYPE_PASSWORD
