name: Sonar Scan

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '14' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: print Java version
        run: java -version
      - name: SonarSource
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: ./gradlew sonarqube -Dsonar.projectKey=OpenAPITools_openapi-style-validator -Dsonar.organization=openapitools -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="$SONAR_LOGIN" --stacktrace