name: Sonar Scan

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '13', '14' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: print Java version
        run: java -version
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: SonarSource
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: ./gradlew sonarqube -Dsonar.projectKey=OpenAPITools_openapi-style-validator -Dsonar.organization=openapitools -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="$SONAR_LOGIN" --stacktrace